### ISSUE TITLE
Crash when starting sinmai

### ISSUE THREAD

**Issue by chenxi050402** [Leapward-Koex/MaiTouchSensorEmulator#1] opened 2024-02-13 05:56 UTC
The program immedietely crashes when starting sinmai
everything is working (connect to port, sensor values and stuff) prior to starting sinmai
using SDEZ 1.35

**Comment by Leapward-Koex** [comment] 2024-02-13 09:50
I'm unable to reproduce this error with my SDEZ 1.35 so I don't think its related to that specific version.

The fact that it crashes on sinmai startup means that its probably the automatic touch panel positioning that's breaking.

Regardless, I've made a new release [v1.02](https://github.com/Leapward-Koex/MaiTouchSensorEmulator/releases/tag/1.0.2) that has better top level error handling, logging, and crash handling.
This build probably wont fix the issue but it will at least give me a starting point to identify the issue.

Please try the new build and if it doesn't work then in the folder next to the WpfMaiTouchEmulator.exe file there should be some .log files and a CrashDump.dmp file if it crashes, attach those here and I'll have a look at it.

**Comment by chenxi050402** [comment] 2024-02-13 22:23
The new version doesn't crash and close itself but it did throw this error, and beside this it works perfectly fine
![image](https://github.com/Leapward-Koex/MaiTouchSensorEmulator/assets/62318879/d8856306-0864-4806-919e-c4ef18683bf8)

**Comment by Leapward-Koex** [comment] 2024-02-14 07:48
Ok I know what's causing this. For whatever reason the emulator can't access the sinmai process, probably because its running as admin or something similar causing some permission issues. There's no real way to get around this issue unless the emulator is also run as admin, which is untested.

The latest version [1.0.3](https://github.com/Leapward-Koex/MaiTouchSensorEmulator/releases/tag/1.0.3) will just give a warning message if this is error is encountered, disable automatic exiting for next time, and just continue on as normal.

**Closed by Leapward-Koex** 2024-02-14 07:48 UTC
